apiVersion: apps/v1
kind: Deployment
metadata:
   name: chatapi_dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatapi_dev
  template:
    metadata:
      labels:
        app: chatapi_dev
    spec:
      containers:
      - name: chatapi_dev
        image: shehan97105/chatapiservice:latest
        ports:
        - containerPort: 5001

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: chatapi
#  labels:
#    app: chatapi
#spec:
#  selector:
#    type: NodePort
#    app: chatapi
#  ports:
#    - protocol: TCP
#      port: 5001
#      targetPort: 5001