apiVersion: apps/v1
kind: Deployment
metadata:
   name: chatapi-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatapi-test
  template:
    metadata:
      labels:
        app: chatapi-test
    spec:
      containers:
      - name: chatapi-test
        image: shehan97105/chatapiservice:v1
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-sc
                key: openai-sc
        ports:
        - containerPort: 5001

