apiVersion: apps/v1
kind: Deployment
metadata:
   name: chatapi-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatapi-test
  template:
    metadata:
      labels:
        app: chatapi-test
    spec:
      containers:
      - name: chatapi-test
        image: shehan97105/chatapiservice:latest
        env:
          - name: OPENAI_API_KEY
            value: "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"
        ports:
        - containerPort: 5001

