apiVersion: apps/v1
kind: Deployment
metadata:
   name: chatapi-prod
   namespace: prod-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapi-prod
  strategry:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: chatapi-prod
    spec:
      containers:
      - name: chatapi-prod
        image: shehan97105/chatapiservice:v7
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-sc
                key: openai-sc
        ports:
        - containerPort: 5001

