apiVersion: apps/v1
kind: Deployment
metadata:
   name: chatapi-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chatapi-prod
  strategry:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: chatapi-prod
    spec:
      containers:
      - name: chatapi-prod
        image: shehan97105/chatapiservice:latest
        env:
          - name: OPENAI_API_KEY
            value: "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"
        ports:
        - containerPort: 5001

